### ISSUE TITLE
How do I apply a band-pass filter?

### ISSUE THREAD

**Issue by YuminosukeSato** [Emotiv/labstreaminglayer#10]
How do I apply a bandpass filter? I would like to apply a bandpass filter from 8 to 30 Hz to the EEG sent by emotiv pro.

**Comment by hoangphamemotiv** [comment]
@YuminosukeSato 
So, you can use EmotivPro-LSL feature to receive data stream from EmotivPro. Then apply your filter to the data stream.

**Comment by YuminosukeSato** [comment]
ok.Thank you.
