### ISSUE TITLE
What variable is EEG data in Python code?

### ISSUE THREAD

**Issue by YuminosukeSato** [Emotiv/labstreaminglayer#11]
I use Emotiv epoc+. Emotiv epoc+ is a 16 channel EEG signal. But sample len is 19 in ReceiveData.py. so where is 16ch EEG data in sample variable?

**Comment by hoangphamemotiv** [comment]
19 channels contains 14 EEG channel already, they are: {"Timestamp", "Counter", "Interpolate", 14 EEG channels  , "HardwareMarker", "Markers" }
You can see more information from: https://github.com/Emotiv/labstreaminglayer

**Comment by YuminosukeSato** [comment]
Thank you.
