### ISSUE TITLE
can not receive LSL signal stream using another laptop

### ISSUE THREAD

**Issue by deltaphase** [Emotiv/labstreaminglayer#12]
Hi.

I have two EPOC Flex headset and would like to simultaneously record EEG data of two participants.

It seems that two headsets can not be connected with the same laptop on EmotivePro (version 3.4.2.444). I try to lunch two EmotivePro windows and they always connect with the first headset.

So I try to use two laptops (windows 10), each one connected with one EPOC Flex headset. Then, I enable the LSL Outlet on both laptops.

I use OpenVibe to receive both LSL streams. However, Openvibe only found the LSL signal stream created on itself.

I also try to use another laptop with the Matlab version of LabRecorder and the LabRecorder app and still can not found any LSL stream from these headset.

Would you mind sharing some suggestions about how to figure it out? Thanks!

**Comment by hoangphamemotiv** [comment]
Hi @deltaphase 
1. About using 2 EmotivPro to connecto to 2 Epoc Flex. 
We supported this. I think the issue come from the auto connect feature in EmotivPro which allow you auto connect pre-headset which you connected before. Can you try this steps:
- EmotivPro 1: connect to Epoc Flex 1
- EmotivPro 2: if it auto connect to Epoc Flex 2, try to disconnect it from "Disconnect" button. and look at "Connect Headset" form to find Epoc Flex 2 to connect to. 

I suggest you using 2 Emotiv Dongles to pair with your Flexes. 
- Plugin Emotiv dongle 1 you to your laptop, power on Flex 1, then ensure it paired with Dongle 1. 
- Plugin Emotiv Dongle 2, Power on Flex 2 and pair it with Dongle 2. 

2. Using 2 Laptop for 2 headsets. It is a good idea also. 

About sending data streams to Matlab and Open Vibe. 
We have detailed document here: 
https://github.com/Emotiv/labstreaminglayer/tree/master/examples/matlab
https://github.com/Emotiv/labstreaminglayer/tree/master/examples/openvibe

you may try with 1 Flex first to make sure it can your and clear about the flow.
