### ISSUE TITLE
How can I obtain a one-second EEG recording using the Emotiv EPOC X headset?

### ISSUE THREAD

**Issue by YuminosukeSato** [Emotiv/labstreaminglayer#14]
How can I obtain a one-second EEG recording using the Emotiv EPOC X headset?
Could you guide me on modifying the sample code to obtain 14 channels of EEG data at a frequency of 256 Hz, for precisely one second?

**Comment by hoangphamemotiv** [comment]
@YuminosukeSato 
You can connect EpocX to Emotivpro app, then use headset setting feature to change data sample rate to 256Hz.

**Comment by YuminosukeSato** [comment]
ok. Thank you.
