### ISSUE TITLE
python maker problem

### ISSUE THREAD

**Issue by Yangdudua** [Emotiv/labstreaminglayer#16]
I use emotiv/LSL/Python/SendMaker.py to send a Maker to the enmtiv pro, but it cannot receive the Maker. I own the emotiv pro license and emotiv flex device

**Comment by hoangphamemotiv** [comment]
Hi @Yangdudua . Did you start a recording on EmotivPro? and what is your license stype?
to enable marker receiver from EmotivPro you need to start a recording

**Comment by PandaQQ** [comment]
Hi @hoangphamemotiv , I'm also having the emotiv pro license and using the demo of  motiv/LSL/Python/SendMaker.py. I also cannot see the redline markers from the readme from the python demo.  There is a bug a lsl side or emotiv side?

As for start a recording on EmotivPro? => I also try with recording and not recording, both cannot see the redline from readme.


The Emotiv Pro Verison is v3.8.0.496.

**Comment by hoangphamemotiv** [comment]
Hi @PandaQQ . If you have a EmotivPro License and created a recording, then it should work. Sorry for asking, did you change or implement new things for the python example? We tested it again and it works fine.

**Comment by PandaQQ** [comment]
@hoangphamemotiv  I have EmotivPro License for student.  And I just use the sample.  I created a recording, may I know the marker line will show real-time or? I using emotiv Pro on MacOS with M2 MAX. 
![marker-added](https://github.com/Emotiv/labstreaminglayer/assets/30284069/476c4f0c-110b-447d-ab93-3edeccc9350b)

**Comment by hoangphamemotiv** [comment]
@PandaQQ . The red lines are markers. And those markers are showing in real time, they are added correctly into EEG data stream.
