### ISSUE TITLE
Is a "Lite" License enough?

### ISSUE THREAD

**Issue by DominiqueMakowski** [Emotiv/labstreaminglayer#18]
Instructions mention "acquire an EmotivPro License". Is a "Lite" (free) license enough?
In other words, can I stream raw EEG data via LSL using the free license and buying only the hardware?

**Comment by Emynguyen-Emotiv** [comment]
Hi! The PRO Lite license is a free license that shows you some basic features of the EmotivPRO app. PRO-Lite only allows you to make a maximum of 5 EEG recordings and the recordings can't be exported, LSL is not available with PRO-Lite either. If you'd like to leverage access raw EEG, export recordings or leverage the Lab Streaming Layer (LSL) feature then you'll need to acquire a paid PRO license. Please contact our support via [this form](https://www.emotiv.com/contact-support/) if you need more information. Thanks!
