### ISSUE TITLE
LSL Outlet Number of Channels

### ISSUE THREAD

**Issue by Lavenderjiang** [Emotiv/labstreaminglayer#3]
Why does EEG outlet have 9 channels for a 5-channel brainware? Also, why does motion sensor outlet have 13 channels? Is there a place to look at what each channel represents? (for example, does the first channel corresponds to sensor AF3 or T7?

**Comment by tungntEmotiv** [comment]
Hi @Lavenderjiang ,

Sorry for late response.
Yes the data include more "Timestamp", "Counter", "Interpolate" and "HardwareMarker" channel beside 5 channels of brainware. The order of channels as below:
`
<channels>
            <channel>
                <label>Timestamp</label>
                <unit>seconds</unit>
                <type>EEG</type>
            </channel>
            <channel>
                <label>Counter</label>
                <unit />
                <type>EEG</type>
            </channel>
            <channel>
                <label>Interpolate</label>
                <unit />
                <type>EEG</type>
            </channel>
            <channel>
                <label>AF3</label>
                <unit>microvolts</unit>
                <type>EEG</type>
            </channel>
            <channel>
                <label>T7</label>
                <unit>microvolts</unit>
                <type>EEG</type>
            </channel>
            <channel>
                <label>Pz</label>
                <unit>microvolts</unit>
                <type>EEG</type>
            </channel>
            <channel>
                <label>T8</label>
                <unit>microvolts</unit>
                <type>EEG</type>
            </channel>
            <channel>
                <label>AF4</label>
                <unit>microvolts</unit>
                <type>EEG</type>
            </channel>
            <channel>
                <label>HardwareMarker</label>
                <unit />
                <type>EEG</type>
            </channel>
        </channels>
`
 And more detail about these channels. Please see https://emotiv.gitbook.io/cortex-api/data-subscription/data-sample-object.

And below is outlet data for motion. There are 12 channels
`<desc>
        <manufacturer>Emotiv</manufacturer>
        <channels>
            <channel>
                <label>Timestamp</label>
                <unit>seconds</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>Counter</label>
                <unit />
                <type>Motion</type>
            </channel>
            <channel>
                <label>Interpolate</label>
                <unit />
                <type>Motion</type>
            </channel>
            <channel>
                <label>GYROX</label>
                <unit>dps</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>GYROY</label>
                <unit>dps</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>GYROZ</label>
                <unit>dps</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>ACCX</label>
                <unit>g</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>ACCY</label>
                <unit>g</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>ACCZ</label>
                <unit>g</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>MAGX</label>
                <unit>microTesla</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>MAGY</label>
                <unit>microTesla</unit>
                <type>Motion</type>
            </channel>
            <channel>
                <label>MAGZ</label>
                <unit>microTesla</unit>
                <type>Motion</type>
            </channel>
        </channels>
    </desc>
`
I will update to the document soon. Thank you for raising issue

**Comment by Lavenderjiang** [comment]
Thank you!
