### ISSUE TITLE
Error using vis_stream.m

### ISSUE THREAD

**Issue by ThireshL** [Emotiv/labstreaminglayer#4]
Hello community, I am using Matlab 2020 version on a windows laptop.
I have Emotiv Pro and Insight headset.
When I try to run **vis_stream.m** file there is an error of unrecognized variable or function.

I have read on StackOverflow and also issues on this repository but still, no leads.

I read in one issue about a similar errors and also did what was mentioned in the solution but did not work.

Any kind of help or direction would be appreciated. 
Thanks in advance

![arg_variable_not_found](https://user-images.githubusercontent.com/57227855/119839882-c755de80-bf04-11eb-80b7-e93953f56c07.JPG)

**Comment by tungntEmotiv** [comment]
Hi @ThireshL ,

Sorry for late response. I suppose the issue similar to https://github.com/Emotiv/labstreaminglayer/issues/2 .  So could you try the below steps:
1) Download lsl matlab library from https://github.com/labstreaminglayer/liblsl-Matlab/releases/ lliblsl-Matlab-lsl1_14-MatlabR2020a-Win64-VS2017.zip . Extract the zip file
2) Replace ./matlab/liblsl-Matlab in emotiv matlab examples folder with the same folder in the extracted folder.
3) Replace all files in ./matlab/bin/win64 in emotiv matlab examples folder by liblsl-Matlab/bin folder in extracted folder.
Please let us know the result.
We also create a ticket to check this issue. We hope to have a better solution. 
Thanks for your patience.

**Comment by ThireshL** [comment]
Thank you for your reply. And it works just fine.
