### ISSUE TITLE
How do I get real-time EEG data in Python?

### ISSUE THREAD

**Issue by YuminosukeSato** [Emotiv/labstreaminglayer#9]
How do I get real-time EEG data in Python?
I am using the emotiv epoc+ and I don't know how to get the recorded brain waves in real time. In particular, in which variable is the EEG stored?

**Comment by hoangphamemotiv** [comment]
hi @YuminosukeSato  there are a few way to get real time EEG in python:
- You can use Cortex API. We have python example: https://github.com/Emotiv/cortex-v2-example/tree/master/python
- You can use EmotivPro-LSL feature (LSL feature on EmotivPro app): with this way you can check Signal Quality on EmotivPro, create a recording, and stream data from EmotivPro to your Python script at the same time: https://github.com/Emotiv/labstreaminglayer/tree/master/examples/python

**Comment by YuminosukeSato** [comment]
Thank you!!!!!
